version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: automatizacion_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/generated_docs:/app/generated_docs
      - ./backend/templates:/app/templates
      - ./backend/sql_app.db:/app/sql_app.db
    environment:
      - DATABASE_URL=sqlite:///sql_app.db
      - BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:80", "http://localhost:3000"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: automatizacion_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
